server:
  port: 8080

spring:
  datasource:
    username: root
    password: Mysqlpass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    hibernate:
        ddl-auto: update
  output:
    ansi:
      enabled: always

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.svetlovka.ru
      name: Svetlovka.Ru
    - url: https://sites.google.com/view/malayarodina
      name: Rodina

connection-settings:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  referrer: https://www.google.com